var negatives = [
    "Confusión",
    "Contempt",
    "Disappointment",
    "Surprise (negative)",
    "Boredom",
    "Doubt",
    "Disgust",
    "Awkwardness",
    "Shame",
    "Anger",
    "Embarrassment",
    "Distress",
    "Sadness",
    "Empathic Pain",
    "Anxiety",
    "Tiredness",
    "Pain",
    "Horror",
    "Guilt",
    "Fear",
    "Envy",
    "Confusion"
];


var positives = [
    "Enthusiasm",
    "Satisfaction",
    "Interest",
    "Admiration",
    "Aesthetic Appreciation",
    "Excitement",
    "Contemplation",
    "Joy",
    "Contentment",
    "Entrancement",
    "Surprise (positive)",
    "Amusement",
    "Triumph",
    "Awe",
    "Pride",
    "Adoration",
    "Concentration",
    "Nostalgia",
    "Realization",
    "Determination",
    "Gratitude",
    "Ecstasy",
    "Calmness",
    "Sarcasm",
    "Disapproval",
    "Annoyance",
    "Craving",
    "Love",
    "Romance",
    "Relief",
    "Desire",
    "Sympathy"
];

